# Generated by Django 5.1.1 on 2024-10-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("active", models.BooleanField()),
                ("vendor", models.TextField()),
                ("model", models.TextField()),
                ("serial", models.TextField()),
                ("firmware_version", models.TextField()),
                ("meter_type", models.TextField()),
                ("meter_serial", models.TextField()),
                ("imsi", models.TextField()),
                ("iccid", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField()),
                ("start_meter_value", models.FloatField()),
                ("end_meter_value", models.FloatField()),
                ("energy_consumption_in_kwh", models.FloatField()),
                ("stop_reason", models.TextField()),
                (
                    "charger",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.chargepoint",
                    ),
                ),
            ],
        ),
    ]
